### ISSUE TITLE
Download Both video and screen for a lecture

### ISSUE THREAD

**Issue by ScottWilliamAnderson** [GeckoDM/GeckoDownloadManager#68]
When downloading a lecture, the extension downloads the screen recording, but not the camera-view of the lecture capture

This is what the Echo360 website looks like:

![image](https://user-images.githubusercontent.com/47524721/70929505-2b475880-202b-11ea-9b79-dea26eb5e6da.png)

Is there any way to download the video recording as well? Either both videos collated into a single mp4 file, or even the two videos as separate mp4 files (then syncing them up would be down the line)

**Comment by ericjiang97** [comment]
Related to #28

**Comment by andreyguenov** [comment]
Do you think you can share an ETA on this feature? Is there something we can do to help the process? :)

**Comment by ericjiang97** [comment]
Hey @andreyguenov ,

Unfortunately not - most of the team is currently unable to work on this issue as we have finished uni and have lost access to Echo360 Cloud, but feel free to fork this repository and make a pull request.

**Comment by imaginebreake** [comment]
> Do you think you can share an ETA on this feature? Is there something we can do to help the process? :)

I do think I will handle this later, but I am working on my exams lately, so feel free to solve this!

**Comment by andreyguenov** [comment]
@ericjiang97 @imaginebreake Thank you guys! For all the amazing work you've done on this tool - it's honestly been a lifesaver! 

Just want to say you've really done outstanding work with this! I probably couldn't solve it myself to be completely honest - just thought I'd reach out and ask if there is anything else I could help out with 😊

@ericjiang97 It's totally understandable that since you've finished school this might no longer be a priority! That's totally OK - thanks for answering here! 👍 😊 

@imaginebreake That's awesome! Of course exams take priority! Fingers crossed you ace them - good luck! Will be looking out for anything in this space - if you can manage to add it at some point that would be awesome! 👍 😊 

Sorry if my initial message sounded entitled or anything - just want to see the tool progress! I appreciate all your work and wish you all the best!

**Comment by ericjiang97** [comment]
Will be closing this PR as this is a duplicate. Please follow this issue on #28 instead.
